mongo3:
  image: mongo
  hostname: mongo3
  expose:
    - "27017"
    - "28017"
  ports:
    - "3019:27017"
  restart: always
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--rest", "--httpinterface" ]

mongo2:
  image: mongo
  hostname: mongo2
  expose:
    - "27017"
    - "28017"
  ports:
    - "3018:27017"
  restart: always
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--rest", "--httpinterface" ]

mongo1:
  image: mongo
  hostname: mongo1
  expose:
    - "27017"
    - "28017"
  links:
    - mongo2:mongo2
    - mongo3:mongo3
  ports:
    - "3017:27017"
  restart: always
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--rest", "--httpinterface" ]
mongosetup:
  image: mongo
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
  volumes:
    - ./scripts:/scripts
  restart: always
  entrypoint: [ "bash", "/scripts/mongosetup.sh" ]
